server:
  forward-headers-strategy: framework
  port: 9023
spring:
  application:
    name: library-management
  aop:
    auto: true
  datasource:
    url: jdbc:mysql://yashgemjewelleries.cbj4aikacpbj.ap-southeast-2.rds.amazonaws.com:3306/ShopManagement
#    url: jdbc:mysql://localhost:3306/do-an4
    username: hoainam
    password: hoainam1212
#    username: root
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tự nhập đê
    password: ko cho passs
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#  api-docs.path: /api-docs
